[build]
builder = "dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "5001"
DB_PATH = "/app/data/presale_contributions.db"
JWT_SECRET = "your-super-secret-jwt-key-change-in-production"
