[build]
builder = "dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "5001"
JWT_SECRET = "your-super-secret-jwt-key-change-in-production"
CORS_ORIGIN = "https://*.railway.app"
# DATABASE_URL will be provided by Railway PostgreSQL service
