name: Deploy to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: false
        
    - name: Clear npm cache and node_modules
      run: |
        npm cache clean --force
        rm -rf node_modules
        rm -rf client/node_modules
        rm -f package-lock.json
        rm -f client/package-lock.json
        
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps --force
        cd client && npm install --legacy-peer-deps --force
        
    - name: Verify TypeScript versions
      run: |
        echo "Root TypeScript version:"
        npm list typescript
        echo "Client TypeScript version:"
        cd client && npm list typescript
        
    - name: Build application
      run: |
        npm run build
        
    - name: Deploy to AWS App Runner
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deploying to AWS App Runner..."
        echo "✅ Build completed successfully"
        echo "📦 Ready for deployment"
